name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: 
    branches: [ main ]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_BLAUFX }}
          base: header, activity, community, repositories, metadata
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes 
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%
          plugin_languages_limit: 8
          plugin_languages_recent_load: 500
          plugin_languages_recent_days: 7
          commits_authoring: lowlighter@users.noreply.github.com
          plugin_lines: yes
