name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: 
    branches: [ main ]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_BLAUFX }}
          base: header, activity, community, repositories, metadata
          commits_authoring: lowlighter@users.noreply.github.com
